name: Release
on:
  push:
    branches:
      - stable
      - beta
      - "*.x"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get-Version
        id: get-version
        uses: shiipou/semantic-release@stable
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.VERSION }}
          release_name: v${{ steps.get-version.outputs.VERSION }}
          body: |
            v${{ steps.get-version.outputs.VERSION }}
          draft: false
          prerelease: v${{ steps.get-version.outputs.IS_PRE_RELEASE }}
